### ISSUE TITLE
Construct Zone Defaults: lapse_rate_tmin and lapse_rate_tmax switched.

### ISSUE THREAD

**Issue by jds485** [laurencelin/RHESSysEastCoast#2]
Line 122 and [123](https://github.com/laurencelin/RHESSysEastCoast/blob/master/init/construct_zone_defaults.c#L123) should be corrected so that tmin matches tmin and tmax matches tmax. This is already fixed in the main RHESSys GitHub.

**Comment by laurencelin** [comment]
Hi Jared, thanks for checking this. Please make a pull and request merge back.
